import {fetchMapData} from "./mapApi.js";import {MAP_MODES,MAP_LAYERS} from "./config.js";import {$,escapeHTML,state} from "./dom.js";
const S={mode:"br",data:null,scale:1,x:0,y:0,drag:false,lastX:0,lastY:0,layers:new Set(MAP_LAYERS.map(x=>x.id))};
function controls(){$("#map-modes").innerHTML=MAP_MODES.map(m=>`<button class="chip ${m.id===S.mode?"active":""}" data-mode="${m.id}">${m.label}</button>`).join("");document.querySelectorAll("[data-mode]").forEach(b=>b.onclick=()=>{S.mode=b.dataset.mode;load()});$("#map-layers").innerHTML=MAP_LAYERS.map(l=>`<label class="layer-row"><input type="checkbox" data-layer="${l.id}" ${S.layers.has(l.id)?"checked":""}><span>${l.label}</span></label>`).join("");document.querySelectorAll("[data-layer]").forEach(i=>i.onchange=()=>{i.checked?S.layers.add(i.dataset.layer):S.layers.delete(i.dataset.layer);markers()})}
function apply(){const c=$("#map-canvas");if(c)c.style.transform=`translate3d(${S.x}px,${S.y}px,0) scale(${S.scale})`}
function fit(){const v=$("#map-viewport"),c=$("#map-canvas");if(!c)return;const w=c.offsetWidth,h=c.offsetHeight;S.scale=Math.min(v.clientWidth/w,v.clientHeight/h)*.92;S.x=(v.clientWidth-w*S.scale)/2;S.y=(v.clientHeight-h*S.scale)/2;apply()}
function markers(){const c=$("#map-canvas");if(!c||!S.data)return;c.querySelectorAll(".map-marker").forEach(x=>x.remove());for(const p of S.data.points){if(!S.layers.has(p.layer))continue;const b=document.createElement("button");b.className=`map-marker ${p.layer}`;b.style.left=p.x*100+"%";b.style.top=p.y*100+"%";b.title=p.name;b.innerHTML="";b.onclick=e=>{e.stopPropagation();const pop=$("#map-popover");pop.innerHTML=`<b>${escapeHTML(p.name)}</b><span>${escapeHTML(p.description||p.layer)}</span>`;pop.hidden=false;pop.style.left=p.x*100+"%";pop.style.top=p.y*100+"%"};c.appendChild(b)}}
function interact(){const v=$("#map-viewport");v.onpointerdown=e=>{S.drag=true;S.lastX=e.clientX;S.lastY=e.clientY;v.setPointerCapture?.(e.pointerId);v.classList.add("dragging")};v.onpointermove=e=>{if(!S.drag)return;S.x+=e.clientX-S.lastX;S.y+=e.clientY-S.lastY;S.lastX=e.clientX;S.lastY=e.clientY;apply()};v.onpointerup=()=>{S.drag=false;v.classList.remove("dragging")};v.onwheel=e=>{e.preventDefault();zoom(e.deltaY<0?1.12:.89,e.clientX,e.clientY)};$("#zoom-in").onclick=()=>zoom(1.15);$("#zoom-out").onclick=()=>zoom(.87);$("#zoom-reset").onclick=fit}
function zoom(mult,cx,cy){const v=$("#map-viewport"),old=S.scale,next=Math.max(.45,Math.min(4,old*mult));if(cx!=null){const r=v.getBoundingClientRect();const px=cx-r.left,py=cy-r.top;S.x=px-(px-S.x)*(next/old);S.y=py-(py-S.y)*(next/old)}S.scale=next;apply()}
function search(){const input=$("#map-search"),results=$("#map-results");input.oninput=()=>{const q=input.value.trim().toLowerCase();results.innerHTML=q?S.data.points.filter(p=>p.name.toLowerCase().includes(q)).slice(0,10).map(p=>`<button data-search-id="${escapeHTML(p.id)}">${escapeHTML(p.name)}</button>`).join(""):"";results.querySelectorAll("[data-search-id]").forEach(b=>b.onclick=()=>{const p=S.data.points.find(x=>x.id===b.dataset.searchId);if(!p)return;S.scale=Math.max(S.scale,1.8);const v=$("#map-viewport");S.x=v.clientWidth/2-p.x*($("#map-canvas").offsetWidth)*S.scale;S.y=v.clientHeight/2-p.y*($("#map-canvas").offsetHeight)*S.scale;apply();input.value=p.name;results.innerHTML=""})}}
async function load(){controls();$("#map-viewport").innerHTML='<div class="map-loading"><div class="skeleton"></div></div>';try{S.data=await fetchMapData(S.mode);$("#map-viewport").innerHTML=`<div id="map-canvas" class="map-canvas"><img id="map-image" src="${S.data.image}" alt="${escapeHTML(S.data.label)}" draggable="false"><div id="map-popover" class="map-popover" hidden></div></div><div class="map-tools"><button id="zoom-in">+</button><button id="zoom-out">−</button><button id="zoom-reset">↺</button></div><div class="map-search"><input id="map-search" placeholder="Search locations"><div id="map-results"></div></div>`;const img=$("#map-image");img.onload=()=>{fit();markers()};img.onerror=()=>{$("#map-viewport").innerHTML=state("Map image unavailable","The API returned map data, but its current image URL could not be loaded.",true)};interact();search()}catch(e){$("#map-viewport").innerHTML=state("Map unavailable",e.message,true)}}
export function init(){load();setInterval(load,30*60*1000)}