import {API} from "./config.js";import {getJSON,walk,firstDate} from "./apiCommon.js";
const IMAGE_KEYS=["featured","icon","smallIcon","large","OfferImage","image","imageUrl"];
const TYPE_KEYS=["displayType","type","backendType","itemType"];
function pick(obj,keys){for(const k of keys){const v=obj?.[k];if(v!==undefined&&v!==null&&v!=="")return v}return null}
function imageOf(obj){let x=pick(obj,["images"]);if(x&&typeof x==="object"){const v=pick(x,IMAGE_KEYS);if(typeof v==="string")return v;for(const v of Object.values(x)){if(typeof v==="string"&&/^https?:/.test(v))return v}}const v=pick(obj,IMAGE_KEYS);return typeof v==="string"?v:null}
function candidateArrays(payload){const out=[];walk(payload,(obj)=>{for(const k of ["entries","items","shop","data"]){if(Array.isArray(obj?.[k]))out.push(obj[k])}});return out}
function normalize(raw,i){const item=raw?.items?.[0]||raw?.brItems?.[0]||raw?.item||raw;const name=pick(raw,["name","displayName","title"])||pick(item,["name","displayName","title"]);if(!name)return null;const price=pick(raw,["finalPrice","regularPrice","price","cost"])??pick(item,["price","cost"]);const rarity=String(pick(item,["rarity"])||pick(raw,["rarity"])||"common").toLowerCase().replace(/\s+/g,"_");const rarityLabel=pick(item,["rarityDisplayValue","displayRarity"])||pick(raw,["rarityDisplayValue","displayRarity"])||rarity.replaceAll("_"," ");const type=pick(item,TYPE_KEYS)||pick(raw,TYPE_KEYS)||"Item";const section=pick(raw,["section","sectionName","layout","displayName"])||"Featured";const set=pick(item,["setText","set"])||pick(raw,["setText","set"]);return{id:String(pick(raw,["offerId","id","devName"])||`${name}-${i}`),name,image:imageOf(raw)||imageOf(item),price:Number(price)||0,rarityValue:rarity,rarityLabel,typeLabel:String(typeof type==="object"?type.displayValue||type.name||"Item":type),setName:typeof set==="object"?set.text||set.name:null||set,isBundle:Boolean(raw.bundle||raw.bundleInfo),sectionName:String(typeof section==="object"?section.name||section.id||"Featured":section)}}
function category(x){const t=x.typeLabel.toLowerCase(),s=x.sectionName.toLowerCase();if(x.isBundle)return"Bundles";if(/outfit|skin/.test(t))return"Outfits";if(/pickaxe|harvesting/.test(t))return"Pickaxes";if(/glider/.test(t))return"Gliders";if(/emote|dance/.test(t))return"Emotes";if(/wrap/.test(t))return"Wraps";if(/daily/.test(s))return"Daily";if(/featured/.test(s))return"Featured";return"Other"}
function build(payload){let raw=[];for(const arr of candidateArrays(payload)){if(arr.length>raw.length)raw=arr}if(!raw.length&&Array.isArray(payload))raw=payload;const seen=new Set(),items=[];raw.map(normalize).filter(Boolean).forEach(x=>{const key=x.id+"|"+x.name;if(!seen.has(key)){seen.add(key);items.push(x)}});if(!items.length)throw new Error("Shop response contained no items");const groups={};items.forEach(x=>(groups[category(x)]??=[]).push(x));const order=["Featured","Daily","Bundles","Outfits","Pickaxes","Gliders","Emotes","Wraps","Other"];return{updatedAt:firstDate(payload),totalItems:items.length,categories:order.filter(k=>groups[k]?.length).map(name=>({name,items:groups[name]}))}}
export async function fetchItemShop({language="en",signal}={}){const sources=[`${API.osirion}/shop/item-shop?lang=${language}`,`${API.fortniteApi}/shop/br?language=${language}`,API.dataminingShop];let last=null;for(const url of sources){try{return build(await getJSON(url,{signal}))}catch(e){last=e}}throw new Error(`Не удалось получить магазин из публичных источников. ${last?.message||"API недоступен"}`)}
